import { e, n, type DiagramProjectData, type ProjectText, type ViewLayout } from './types';

// Depósitos CPS (stock entre depósitos y obras): cinco vistas.

const layout: ViewLayout[] = [
  {
    // Tres tipos de usuario caen rectos sobre una app ancha; la base debajo; lo
    // que sale de la app (avisos, papeles, tipo de cambio) a la derecha.
    id: 'mapa',
    nodes: [
      n('consulta', 'persona', 40, 60, 220),
      n('operario', 'persona', 300, 60, 220),
      n('admin', 'persona', 560, 60, 220),
      n('app', 'servidor', 40, 300, 740),
      n('base', 'datos', 40, 560, 740),
      n('alertas', 'gate', 900, 60, 240),
      n('pdf', 'fabrica', 900, 300, 240),
      n('bcu', 'fabrica', 900, 560, 240),
    ],
    groups: [
      { id: 'gq', nodes: ['consulta', 'operario', 'admin'] },
      { id: 'ga', nodes: ['app', 'base'] },
      { id: 'gx', nodes: ['alertas', 'pdf', 'bcu'] },
    ],
    edges: [
      e('consulta', 'app'),
      e('operario', 'app'),
      e('admin', 'app'),
      e('app', 'base', { bidir: true }),
      e('app', 'alertas'),
      e('app', 'pdf'),
      e('app', 'bcu', { dashed: true }),
    ],
    tour: [
      { nodes: ['consulta', 'operario', 'admin', 'app'], edges: ['consulta>app', 'operario>app', 'admin>app'] },
      { nodes: ['app'], edges: [] },
      { nodes: ['app', 'base'], edges: ['app>base'] },
      { nodes: ['app', 'pdf', 'bcu'], edges: ['app>pdf', 'app>bcu'] },
      { nodes: ['app', 'alertas'], edges: ['app>alertas'] },
    ],
  },
  {
    // La cadena del material en una fila; quién interviene arriba, otras
    // entradas al stock abajo, todo con flechas rectas.
    id: 'circuito',
    nodes: [
      n('obra', 'persona', 40, 60, 200),
      n('proveedor', 'fabrica', 700, 60, 200),
      n('camion', 'fabrica', 1360, 60, 200),
      n('obra2', 'persona', 2350, 60, 200),
      n('pedido', 'paso', 40, 300, 200),
      n('oc', 'paso', 370, 300, 200),
      n('recepcion', 'paso', 700, 300, 200),
      n('deposito', 'datos', 1030, 300, 200),
      n('transferencia', 'paso', 1360, 300, 200),
      n('recepdest', 'paso', 1690, 300, 200),
      n('vale', 'paso', 2020, 300, 200),
      n('rendicion', 'paso', 2350, 300, 200),
      n('entrada', 'entrada', 910, 560, 180),
      n('ajuste', 'entrada', 1150, 560, 180),
    ],
    groups: [
      { id: 'gc', nodes: ['pedido', 'oc', 'recepcion', 'deposito', 'transferencia', 'recepdest', 'vale', 'rendicion'] },
      { id: 'gq', nodes: ['obra', 'proveedor', 'camion', 'obra2'] },
      { id: 'go', nodes: ['entrada', 'ajuste'] },
    ],
    edges: [
      e('obra', 'pedido'),
      e('pedido', 'oc'),
      e('oc', 'recepcion'),
      e('proveedor', 'recepcion'),
      e('recepcion', 'deposito'),
      e('entrada', 'deposito'),
      e('ajuste', 'deposito'),
      e('deposito', 'transferencia'),
      e('camion', 'transferencia'),
      e('transferencia', 'recepdest'),
      e('recepdest', 'vale'),
      e('vale', 'obra2'),
      e('vale', 'rendicion'),
      e('rendicion', 'obra2'),
    ],
    tour: [
      { nodes: ['obra', 'pedido', 'oc'], edges: ['obra>pedido', 'pedido>oc'] },
      { nodes: ['oc', 'proveedor', 'recepcion', 'deposito'], edges: ['oc>recepcion', 'proveedor>recepcion', 'recepcion>deposito'] },
      { nodes: ['deposito', 'camion', 'transferencia', 'recepdest'], edges: ['deposito>transferencia', 'camion>transferencia', 'transferencia>recepdest'] },
      { nodes: ['recepdest', 'vale', 'obra2', 'rendicion'], edges: ['recepdest>vale', 'vale>obra2', 'vale>rendicion', 'rendicion>obra2'] },
      { nodes: ['entrada', 'ajuste', 'deposito'], edges: ['entrada>deposito', 'ajuste>deposito'] },
    ],
  },
  {
    // La cadena del asiento en el centro; garantías a la izquierda; lo que se
    // deriva a la derecha, fila por fila.
    id: 'kardex',
    nodes: [
      n('anular', 'gate', 40, 420, 220),
      n('concurrencia', 'gate', 40, 600, 220),
      n('operacion', 'paso', 400, 60, 280),
      n('documento', 'datos', 400, 240, 280),
      n('movimientos', 'datos', 400, 420, 280),
      n('saldos', 'datos', 400, 600, 280),
      n('reportes', 'web', 400, 780, 280),
      n('ppp', 'calc', 800, 420, 280),
      n('virtuales', 'datos', 800, 600, 280),
      n('valorizado', 'total', 800, 780, 280),
    ],
    groups: [
      { id: 'gk', nodes: ['operacion', 'documento', 'movimientos', 'saldos', 'reportes'] },
      { id: 'gr', nodes: ['ppp', 'virtuales', 'valorizado'] },
      { id: 'gg', nodes: ['anular', 'concurrencia'] },
    ],
    edges: [
      e('operacion', 'documento'),
      e('documento', 'movimientos'),
      e('movimientos', 'saldos'),
      e('saldos', 'reportes'),
      e('anular', 'movimientos'),
      e('concurrencia', 'saldos'),
      e('movimientos', 'ppp'),
      e('saldos', 'virtuales'),
      e('reportes', 'valorizado'),
    ],
    tour: [
      { nodes: ['operacion', 'documento'], edges: ['operacion>documento'] },
      { nodes: ['documento', 'movimientos', 'anular'], edges: ['documento>movimientos', 'anular>movimientos'] },
      { nodes: ['movimientos', 'saldos', 'concurrencia', 'virtuales'], edges: ['movimientos>saldos', 'concurrencia>saldos', 'saldos>virtuales'] },
      { nodes: ['movimientos', 'ppp'], edges: ['movimientos>ppp'] },
      { nodes: ['saldos', 'reportes', 'valorizado'], edges: ['saldos>reportes', 'reportes>valorizado'] },
    ],
  },
  {
    // El ciclo de vida de una unidad en una fila; los cuatro destinos al rendir
    // apilados a la derecha, en abanico.
    id: 'herramientas',
    nodes: [
      n('serie', 'datos', 40, 300, 240),
      n('disponible', 'ok', 400, 300, 200),
      n('vale', 'paso', 720, 300, 220),
      n('enobra', 'estado', 1060, 300, 200),
      n('rendicion', 'paso', 1380, 300, 220),
      n('devuelta', 'ok', 1720, 100, 200),
      n('areparacion', 'estado', 1720, 260, 200),
      n('rota', 'bad', 1720, 420, 200),
      n('perdida', 'bad', 1720, 560, 200),
      n('baja', 'bad', 2040, 260, 200),
    ],
    groups: [
      { id: 'gc', nodes: ['serie', 'disponible', 'vale', 'enobra', 'rendicion'] },
      { id: 'gr', nodes: ['devuelta', 'areparacion', 'rota', 'perdida', 'baja'] },
    ],
    edges: [
      e('serie', 'disponible'),
      e('disponible', 'vale'),
      e('vale', 'enobra'),
      e('enobra', 'rendicion'),
      e('rendicion', 'devuelta'),
      e('rendicion', 'areparacion'),
      e('rendicion', 'rota'),
      e('rendicion', 'perdida'),
      e('areparacion', 'baja', { dashed: true }),
    ],
    tour: [
      { nodes: ['serie', 'disponible'], edges: ['serie>disponible'] },
      { nodes: ['disponible', 'vale', 'enobra'], edges: ['disponible>vale', 'vale>enobra'] },
      { nodes: ['enobra', 'rendicion', 'devuelta', 'areparacion', 'rota', 'perdida'], edges: ['enobra>rendicion', 'rendicion>devuelta', 'rendicion>areparacion', 'rendicion>rota', 'rendicion>perdida'] },
      { nodes: ['areparacion', 'baja'], edges: ['areparacion>baja'] },
    ],
  },
  {
    // Roles a la izquierda, capas en el centro, el camino de un push a la
    // derecha. Las pruebas y las migraciones llegan a las tablas por el costado.
    id: 'arquitectura',
    nodes: [
      n('admin', 'persona', 40, 60, 240),
      n('operario', 'persona', 40, 220, 240),
      n('consulta', 'persona', 40, 380, 240),
      n('ui', 'web', 340, 60, 560),
      n('api', 'servidor', 340, 220, 560),
      n('rpc', 'calc', 340, 380, 560),
      n('tablas', 'datos', 340, 540, 560),
      n('push', 'config', 1000, 60, 260),
      n('ci', 'gate', 1000, 220, 260),
      n('migraciones', 'datos', 1000, 380, 260),
      n('coolify', 'config', 1320, 220, 240),
      n('smoke', 'calc', 1000, 540, 260),
    ],
    groups: [
      { id: 'gq', nodes: ['admin', 'operario', 'consulta'] },
      { id: 'gl', nodes: ['ui', 'api', 'rpc', 'tablas'] },
      { id: 'gd', nodes: ['push', 'ci', 'migraciones', 'coolify'] },
    ],
    edges: [
      e('admin', 'ui'),
      e('operario', 'ui'),
      e('consulta', 'ui'),
      e('ui', 'api', { bidir: true }),
      e('api', 'rpc'),
      e('rpc', 'tablas'),
      e('push', 'ci'),
      e('ci', 'migraciones'),
      e('push', 'coolify'),
      e('migraciones', 'tablas', { dashed: true }),
      e('smoke', 'tablas', { dashed: true }),
    ],
    tour: [
      { nodes: ['admin', 'operario', 'consulta', 'ui'], edges: ['admin>ui', 'operario>ui', 'consulta>ui'] },
      { nodes: ['ui', 'api', 'rpc', 'tablas'], edges: ['ui>api', 'api>rpc', 'rpc>tablas'] },
      { nodes: ['smoke', 'tablas'], edges: ['smoke>tablas'] },
      { nodes: ['push', 'ci', 'migraciones', 'coolify', 'tablas'], edges: ['push>ci', 'ci>migraciones', 'push>coolify', 'migraciones>tablas'] },
    ],
  },
];

/* ───────────────────────────── Textos por idioma ──────────────────────────── */

const es: ProjectText = {
  header: {
    kicker: 'case study · depósitos cps',
    title: 'El stock, en un diagrama que se puede tocar.',
    intro:
      'Cinco vistas del sistema de depósitos: quién lo usa y qué hay detrás, el circuito del material del pedido a la obra, cómo se asienta y se valoriza cada movimiento, la vida de una herramienta con número de serie y cómo está construido. Cada caja se puede mover; cada vista tiene un recorrido explicado paso a paso.',
    footNote: 'El diagrama describe el mecanismo del sistema, no datos de la empresa. El código es interno de Grupo CPS.',
  },
  typeNames: {
    persona: 'persona',
    web: 'pantalla',
    servidor: 'aplicación',
    datos: 'datos',
    panel: 'pantalla',
    fabrica: 'afuera de la app',
    paso: 'paso',
    calc: 'regla en la base',
    total: 'resultado',
    entrada: 'entrada',
    gate: 'garantía',
    config: 'infraestructura',
    estado: 'estado',
    ok: 'estado',
    bad: 'estado',
  },
  views: {
    mapa: {
      name: 'Mapa general',
      intro:
        'Tres tipos de usuario, una app con una pantalla por operación y una base de datos donde viven todas las reglas. Lo que sale hacia afuera: avisos, papeles para el circuito físico y el tipo de cambio.',
      script: [
        'Es el sistema de stock de Grupo CPS: qué hay, dónde está y a qué obra se fue. Reemplazó planillas, mensajes y memoria.',
        'Lo usan tres perfiles: los jefes de obra y la dirección consultan y piden compras; logística y depósito cargan compras, transferencias, vales y ajustes; el admin además administra usuarios.',
        'Nadie escribe «quedan 40 bolsas». Cada cambio nace de un comprobante numerado que asienta un movimiento en un kardex inmutable; el saldo por depósito se deriva de ahí y el stock negativo es imposible por diseño.',
        'Todas las reglas viven en la base de datos, en funciones transaccionales: la interfaz solo las llama. Por eso aunque alguien hablara directo con la API no puede saltearse ninguna.',
        'Y el circuito físico también está adentro: órdenes de compra, recepciones y vales en PDF con lugar para firmas, tipo de cambio oficial para las compras en dólares y alertas de pedidos vencidos, transferencias demoradas y stock bajo mínimo.',
      ],
      nodes: {
        consulta: {
          label: 'Jefes de obra y dirección',
          sub: 'rol consulta: leen todo, piden compras',
          desc: 'Quienes necesitan saber qué hay y pedir material. Ven todo el sistema y solo escriben sus propios pedidos de compra y las preferencias de su dashboard.',
        },
        operario: {
          label: 'Logística y depósito',
          sub: 'rol operario: cargan movimientos y catálogos',
          desc: 'Quienes mueven el material. Cargan compras, recepciones, transferencias, vales, ajustes y catálogos, y atienden los pedidos de compra de cualquiera. No tocan usuarios.',
        },
        admin: {
          label: 'Administrador',
          sub: 'todo lo anterior y además crea usuarios y roles',
          desc: 'El único que administra usuarios. El registro público está cerrado: los perfiles nacen inactivos hasta que un admin los activa.',
        },
        app: {
          label: 'App web',
          sub: 'pedidos · compras · transferencias · vales · herramientas · ajustes · kardex · dashboard con widgets y alertas',
          desc: 'Una pantalla por operación y consultas en vivo. La interfaz nunca calcula stock ni costos: se los pide a la base.',
          bullets: [
            'Dashboard armable por usuario, con los widgets que le sirven a cada uno.',
            'Kardex por depósito u obra en cualquier período; un artículo en todos los depósitos a la vez.',
            'Ocultar botones por rol es ergonomía: la autorización real está en la base.',
          ],
        },
        base: {
          label: 'Base de datos (PostgreSQL)',
          sub: 'funciones transaccionales · kardex inmutable · saldos por depósito · seguridad por fila',
          desc: 'Acá viven todas las reglas de negocio. Cada operación es una función que valida el rol y las reglas y asienta el movimiento, todo en una transacción.',
          bullets: [
            'Las tablas de movimientos no tienen políticas de escritura: la única puerta son las funciones.',
            'El kardex solo se inserta; corregir es contra-asentar.',
            'Costeo por precio promedio ponderado, congelado en cada movimiento.',
          ],
        },
        alertas: {
          label: 'Alertas',
          sub: 'pedidos vencidos o por vencer · transferencias demoradas · stock bajo mínimo',
          desc: 'Se derivan del estado real, no de recordatorios cargados a mano. Aparecen en la campanita del sistema.',
        },
        pdf: {
          label: 'Papeles del circuito físico',
          sub: 'orden de compra, recepción y vale en PDF con lugar para firmas',
          desc: 'El proveedor, el camión y la obra firman en papel. El PDF sale del mismo documento que asienta el movimiento.',
        },
        bcu: {
          label: 'Tipo de cambio oficial',
          sub: 'para compras en dólares, con caché del día',
          desc: 'Las compras conviven en pesos y dólares con su moneda registrada; el sistema toma la cotización oficial de la fecha y la guarda.',
        },
      },
      edges: {
        'consulta>app': 'consultan y piden',
        'operario>app': 'cargan movimientos',
        'admin>app': 'administra',
        'app>base': 'cada operación es una función en la base',
        'app>alertas': 'avisa',
        'app>pdf': 'imprime',
        'app>bcu': 'consulta',
      },
      groups: { gq: 'QUIÉN USA', ga: 'LA APLICACIÓN', gx: 'HACIA AFUERA' },
      tour: [
        'Tres tipos de usuario entran a la misma app: los jefes de obra y la dirección consultan y piden compras; logística y depósito cargan todos los movimientos; el admin además administra usuarios.',
        'La app tiene una pantalla por operación: pedidos, compras, transferencias, vales, herramientas, ajustes, kardex y un dashboard con widgets y alertas.',
        'Ninguna pantalla calcula stock: cada operación es una función transaccional en la base, que valida el rol y las reglas y asienta el movimiento en un kardex inmutable.',
        'El circuito físico también es parte: órdenes de compra, recepciones y vales salen en PDF con lugar para firmas, y las compras en dólares toman el tipo de cambio oficial del día.',
        'Y el sistema avisa solo: pedidos vencidos o por vencer, transferencias demoradas y stock bajo mínimo, derivados del estado real.',
      ],
    },
    circuito: {
      name: 'El circuito del material',
      intro:
        'Del pedido de una obra a la rendición de lo que se usó, cada paso es un documento numerado con su propio estado. Arriba, quién interviene en cada tramo; abajo, las otras formas de que entre stock.',
      nodes: {
        obra: { label: 'Jefe de obra', sub: 'pide lo que necesita, con destino y fecha límite', desc: 'Cualquier usuario puede pedir; logística decide cómo comprarlo.' },
        proveedor: { label: 'Proveedor', sub: 'entrega contra la orden de compra', desc: 'Puede haber varios en una misma orden: los renglones se compran a quien convenga y alimentan un histórico de precios por artículo y proveedor.' },
        camion: { label: 'Camión y personas', sub: 'asignados al traslado', desc: 'Cada transferencia registra el camión y las personas que viajan con el material.' },
        obra2: { label: 'Obra', sub: 'recibe el material y responde por él', desc: 'Lo consumido se imputa al gasto de la obra; lo que vuelve reingresa al stock.' },
        pedido: {
          label: 'Pedido de compra',
          sub: 'abierto → en proceso → atendido | cancelado',
          desc: 'Lo que una obra o un depósito necesita, con destino y fecha límite. Logística lo atiende armando órdenes de compra o puede cancelarlo con motivo.',
        },
        oc: {
          label: 'Orden de compra',
          sub: 'borrador → emitida → recepción parcial → recibida → cerrada | cancelada',
          desc: 'Renglones que pueden ir a distintos proveedores. Al emitirla fija los precios en el histórico; sale en PDF con lugar para firmas.',
          bullets: ['Cerrar con faltantes es una decisión explícita, con motivo.', 'Cerrada es terminal: no se reabre.'],
        },
        recepcion: {
          label: 'Recepción por tandas',
          sub: 'lo que llegó en cada entrega; puede ser parcial',
          desc: 'Cada tanda asienta la entrada al depósito al costo de la orden. Anular una recepción genera el asiento inverso.',
        },
        deposito: {
          label: 'Depósito',
          sub: 'saldo por artículo, mantenido por la base',
          desc: 'El saldo no se edita: es la suma de los movimientos. Incluye los depósitos virtuales EN TRÁNSITO y REPARACIÓN.',
        },
        transferencia: {
          label: 'Transferencia «en viaje»',
          sub: 'en tránsito → recepción parcial → recibida | cancelada',
          desc: 'Mientras viaja, el material no está en ninguno de los dos depósitos: está en EN TRÁNSITO, con camión y personas asignados.',
        },
        recepdest: {
          label: 'Recepción en destino',
          sub: 'por tandas, con cierre por faltantes',
          desc: 'El destino recibe de a tandas; lo que no llegó se da de baja explícitamente, con motivo.',
        },
        vale: {
          label: 'Vale de consumo',
          sub: 'abierto → rendido | anulado',
          desc: 'Lo que sale del depósito hacia una obra. Las herramientas van por número de serie.',
        },
        rendicion: {
          label: 'Rendición',
          sub: 'lo usado se imputa a la obra; lo que vuelve reingresa al costo del vale',
          desc: 'Cierra el vale: cada renglón dice cuánto se usó y cuánto volvió. La rendición tiene que cuadrar.',
        },
        entrada: { label: 'Entrada directa', sub: 'stock que llega sin orden de compra', desc: 'Con costo y motivo; mismo asiento que una recepción.' },
        ajuste: { label: 'Ajuste de inventario', sub: 'diferencias de conteo, con motivo obligatorio', desc: 'Suma o resta con su documento numerado. Nunca una edición del saldo.' },
      },
      edges: {
        'obra>pedido': 'pide',
        'pedido>oc': 'logística arma',
        'oc>recepcion': 'por tandas',
        'proveedor>recepcion': 'entrega',
        'recepcion>deposito': 'suma stock al costo',
        'entrada>deposito': 'sin orden',
        'ajuste>deposito': 'con motivo',
        'deposito>transferencia': 'sale',
        'camion>transferencia': 'viaja',
        'transferencia>recepdest': 'en tránsito',
        'recepdest>vale': 'desde el depósito',
        'vale>obra2': 'sale a obra',
        'vale>rendicion': 'se rinde',
        'rendicion>obra2': 'lo usado se imputa',
      },
      groups: { gc: 'EL CIRCUITO DEL MATERIAL', gq: 'QUIÉN INTERVIENE', go: 'OTRAS ENTRADAS AL STOCK' },
      tour: [
        'Empieza con un pedido: cualquier usuario, también un jefe de obra, pide lo que necesita con destino y fecha límite. Logística lo atiende armando órdenes de compra.',
        'La orden fija precios y sale en PDF. El proveedor entrega de a tandas: cada recepción suma stock al depósito al costo de la orden; cerrar con faltantes es una decisión explícita.',
        'Cuando el material va de un depósito a otro pasa por un estado real: en tránsito, con camión y personas. Recién al recibirse en destino cuenta allá.',
        'Lo que sale a obra va por vale y se rinde: lo usado se imputa al gasto de la obra y lo que vuelve reingresa al costo congelado del vale.',
        'También entra stock sin orden de compra y se ajusta por diferencias de conteo, siempre con documento y motivo. Nunca editando el saldo.',
      ],
    },
    kardex: {
      name: 'Kardex y costeo',
      intro:
        'La cadena que convierte una operación en un número defendible: documento, movimiento inmutable, saldo por depósito y reportes. A los costados, las garantías y lo que se deriva.',
      nodes: {
        operacion: { label: 'Una operación', sub: 'compra recibida, transferencia, vale, rendición, ajuste…', desc: 'Cualquier cosa que cambie el stock entra por acá.' },
        documento: {
          label: 'Documento numerado',
          sub: 'tipo (OC, RC, EN, TR, VA, AJ, RP…), número correlativo, usuario y fecha',
          desc: 'El número lo asigna la base de forma atómica: dos operaciones simultáneas jamás lo comparten.',
        },
        movimientos: {
          label: 'Movimientos de stock',
          sub: 'solo se insertan; corregir es contra-asentar',
          desc: 'El kardex. Cada fila dice artículo, depósito, cantidad con signo, costo congelado y el documento que la explica.',
        },
        saldos: {
          label: 'Saldos por depósito',
          sub: 'los mantiene un trigger · cantidad ≥ 0 siempre',
          desc: 'Derivados de los movimientos, nunca editados. La restricción en la tabla hace imposible el stock negativo.',
        },
        reportes: {
          label: 'Reportes',
          sub: 'kardex a una fecha · un artículo en todos los depósitos · stock por obra',
          desc: 'Todo se responde desde los movimientos: qué había en tal depósito tal día, adónde fue cada unidad.',
        },
        anular: {
          label: 'Anular',
          sub: 'genera el asiento inverso; la historia queda',
          desc: 'No existe la corrección silenciosa. Anular una recepción, un vale o una rendición inserta el movimiento contrario, con motivo.',
        },
        concurrencia: {
          label: 'Dos operaciones a la vez',
          sub: 'los locks van en orden fijo; la restricción impide el negativo',
          desc: 'Las funciones toman los renglones siempre en el mismo orden para no bloquearse entre sí, y si dos consumos compiten por el mismo stock, el segundo falla en vez de dejar saldo negativo.',
        },
        ppp: {
          label: 'Costo promedio ponderado',
          sub: 'por artículo, congelado en cada movimiento',
          desc: 'Cada entrada con costo mueve el promedio; cada salida toma el costo del momento y lo deja escrito.',
          bullets: [
            'La transferencia no altera el promedio.',
            'La devolución de un vale reingresa al costo del vale.',
            'La carga inicial sin valorizar no lo toca.',
          ],
        },
        virtuales: {
          label: 'Depósitos virtuales',
          sub: 'EN TRÁNSITO y REPARACIÓN',
          desc: 'Lo que viaja o está en el service también es stock. Así la suma de todos los saldos siempre iguala el stock real de la empresa.',
        },
        valorizado: {
          label: 'Stock valorizado',
          sub: 'cantidad × costo promedio, por depósito y por obra',
          desc: 'Un número que se puede defender: sale de movimientos con costo congelado, no de una estimación.',
        },
      },
      edges: {
        'operacion>documento': 'numerado, con usuario y fecha',
        'documento>movimientos': 'asienta',
        'movimientos>saldos': 'trigger',
        'saldos>reportes': 'se consultan',
        'anular>movimientos': 'contra-asiento',
        'concurrencia>saldos': 'cantidad ≥ 0',
        'movimientos>ppp': 'costo del momento',
        'saldos>virtuales': 'también son saldos',
        'reportes>valorizado': 'costo congelado',
      },
      groups: { gk: 'LA CADENA', gr: 'LO QUE SE DERIVA', gg: 'GARANTÍAS' },
      tour: [
        'Toda operación nace como un documento numerado, con usuario y fecha. El número lo asigna la base de forma atómica.',
        'El documento asienta movimientos en el kardex, que solo se inserta. Corregir es generar el contra-asiento: la historia queda completa.',
        'Un trigger mantiene los saldos por depósito y una restricción hace imposible el negativo, incluso con dos operaciones a la vez. Lo que viaja o está en el service también es saldo, en depósitos virtuales.',
        'Cada movimiento lleva su costo congelado, con promedio ponderado por artículo: las transferencias no lo alteran y las devoluciones vuelven al costo del vale.',
        'Por eso los reportes son números defendibles: kardex a una fecha, un artículo en todos los depósitos y stock valorizado por depósito y por obra.',
      ],
    },
    herramientas: {
      name: 'Herramientas por serie',
      intro:
        'Una amoladora no es «3 amoladoras»: es esta, con su número de serie. Cada unidad tiene su ciclo de vida y alguien responde por ella.',
      nodes: {
        serie: { label: 'Unidad con número de serie', sub: 'cada herramienta física, una fila propia', desc: 'Las herramientas se cargan por unidad; los materiales, por cantidad.' },
        disponible: { label: 'Disponible', sub: 'en un depósito', desc: 'Lista para salir por vale.' },
        vale: { label: 'Sale por vale', sub: 'a una obra, unidad por unidad', desc: 'El vale nombra cada serie que se lleva.' },
        enobra: { label: 'En obra', sub: 'la obra responde por ella', desc: 'Mientras está afuera figura en el depósito de la obra.' },
        rendicion: { label: 'Rendición', sub: 'unidad por unidad, con un resultado cada una', desc: 'Al rendir el vale, cada herramienta vuelve, va a reparación, o se declara rota o perdida.' },
        devuelta: { label: 'Devuelta', sub: 'vuelve a disponible', desc: 'Reingresa al depósito de origen.' },
        areparacion: {
          label: 'A reparación',
          sub: 'orden de reparación · depósito virtual REPARACIÓN',
          desc: 'La unidad pasa al service con su orden. Si vuelve reparada queda disponible de nuevo; si no, se da de baja.',
        },
        rota: { label: 'Rota', sub: 'se imputa a la obra', desc: 'Sale del stock y queda cargada a la obra que la tenía.' },
        perdida: { label: 'Perdida', sub: 'se imputa a la obra', desc: 'Igual que rota: baja del stock con responsable.' },
        baja: { label: 'Baja', sub: 'descartada tras la reparación', desc: 'El service la declaró irrecuperable.' },
      },
      edges: {
        'serie>disponible': 'se da de alta',
        'disponible>vale': 'sale por vale',
        'vale>enobra': 'llega',
        'enobra>rendicion': 'se rinde',
        'areparacion>baja': 'sin arreglo',
      },
      groups: { gc: 'CICLO DE VIDA', gr: 'QUÉ PUEDE PASAR AL RENDIR' },
      tour: [
        'Cada herramienta es una unidad con número de serie y una fila propia; los materiales, en cambio, se cuentan por cantidad.',
        'Sale a la obra por vale, nombrada serie por serie, y mientras está afuera figura en el depósito de esa obra.',
        'Al rendir el vale, cada unidad tiene un destino: vuelve al depósito, va a reparación, o se declara rota o perdida. Rota y perdida se imputan a la obra que la tenía.',
        'Las que van a reparación pasan al depósito virtual REPARACIÓN con su orden: si vuelven reparadas quedan disponibles; si no, se dan de baja.',
      ],
    },
    arquitectura: {
      name: 'Cómo está hecho',
      intro:
        'Las reglas viven en la base de datos, no en la interfaz. Quién entra, qué capas atraviesa una operación y qué pasa con cada push a producción.',
      nodes: {
        admin: { label: 'Admin', sub: 'opera, administra catálogos y usuarios' },
        operario: { label: 'Operario', sub: 'logística y depósito: carga todo, no toca usuarios' },
        consulta: { label: 'Consulta', sub: 'jefes de obra y dirección: lee todo, escribe sus pedidos' },
        ui: {
          label: 'Pantallas (Next.js)',
          sub: 'server actions que devuelven éxito o fallo, nunca lanzan · gates de rol como ergonomía',
          desc: 'La interfaz muestra y pide. No calcula stock, costos ni estados.',
        },
        api: {
          label: 'Supabase self-hosted',
          sub: 'login por usuario · registro cerrado · perfiles nacen inactivos hasta que un admin activa',
          desc: 'PostgreSQL, autenticación y API corriendo en el propio servidor de la empresa, no en una nube de terceros.',
        },
        rpc: {
          label: 'Funciones transaccionales',
          sub: 'validan rol y reglas en una transacción · error con código y mensaje humano',
          desc: 'Cada operación es una función. La primera línea verifica que quien llama puede cargar; los errores de negocio tienen código y su traducción para la persona.',
        },
        tablas: {
          label: 'Tablas con seguridad por fila',
          sub: 'las de movimientos no tienen políticas de escritura: la única puerta son las funciones',
          desc: 'Aunque alguien hablara directo con la API, no puede insertar un movimiento por fuera de las reglas.',
        },
        push: { label: 'Push a main', sub: 'un solo camino a producción' },
        ci: {
          label: 'Verificación en CI',
          sub: 'typecheck, lint y la suite SQL, con las migraciones aplicadas desde cero',
          desc: 'Corre en cada pull request y en cada push. Si falla, producción no se toca.',
        },
        migraciones: { label: 'Migraciones a producción', sub: 'solo si la verificación pasó', desc: 'El esquema está versionado; una regla de negocio nueva es una migración, no un condicional en la interfaz.' },
        coolify: { label: 'La app se redeploya', sub: 'automático, sin downtime', desc: 'El contenedor nuevo lleva el SHA del commit para saber qué versión corre.' },
        smoke: {
          label: 'Suite de humo en SQL',
          sub: 'corre en una transacción que se revierte · ~160 aserciones',
          desc: 'Prueba el núcleo real contra la base real sin ensuciarla: numeración, costeo, recepciones parciales, rendiciones, herramientas por serie, roles y permisos.',
        },
      },
      edges: {
        'ui>api': 'sesión + llamadas',
        'api>rpc': 'cada operación',
        'rpc>tablas': 'asienta',
        'push>ci': 'verifica',
        'ci>migraciones': 'si pasa',
        'push>coolify': 'redeploya',
        'migraciones>tablas': 'esquema',
        'smoke>tablas': 'prueba',
      },
      groups: { gq: 'QUIÉN ENTRA', gl: 'CAPAS', gd: 'CADA PUSH A MAIN' },
      tour: [
        'Tres roles entran por las mismas pantallas; la interfaz oculta lo que no corresponde, pero eso es ergonomía: la autorización real está más abajo.',
        'Una operación baja por las capas: la pantalla llama, la API autentica, la función transaccional valida rol y reglas, y recién ahí se asienta en tablas que nadie puede escribir por otro camino.',
        'El núcleo se prueba donde vive: una suite en SQL corre dentro de una transacción que se revierte, contra la base real.',
        'Cada push a main pasa por la verificación en CI con las migraciones aplicadas desde cero; solo si sale en verde se aplican a producción. La app se redeploya sola.',
      ],
    },
  },
};

const en: ProjectText = {
  header: {
    kicker: 'case study · cps warehouses',
    title: 'The stock system, in a diagram you can move around.',
    intro:
      'Five views of the warehouse system: who uses it and what sits behind it, the material circuit from request to site, how every movement is recorded and valued, the life of a serial-numbered tool and how it is built. Every box can be dragged; every view has a step-by-step walkthrough.',
    footNote: 'The diagram describes how the system works, not company data. The code is internal to Grupo CPS.',
  },
  typeNames: {
    persona: 'person',
    web: 'screen',
    servidor: 'application',
    datos: 'data',
    panel: 'screen',
    fabrica: 'outside the app',
    paso: 'step',
    calc: 'rule in the database',
    total: 'result',
    entrada: 'input',
    gate: 'guarantee',
    config: 'infrastructure',
    estado: 'status',
    ok: 'status',
    bad: 'status',
  },
  views: {
    mapa: {
      name: 'Overview',
      intro:
        'Three kinds of user, one app with a screen per operation, and a database where every rule lives. What goes out: alerts, paperwork for the physical circuit and the exchange rate.',
      script: [
        'It is Grupo CPS’s stock system: what there is, where it is and which site it went to. It replaced spreadsheets, messages and memory.',
        'Three profiles use it: site managers and management look things up and request purchases; logistics and warehouse staff record purchases, transfers, vouchers and adjustments; the admin also manages users.',
        'Nobody types “40 bags left”. Every change is born from a numbered document that records a movement in an immutable ledger; the balance per warehouse is derived from it, and negative stock is impossible by design.',
        'Every rule lives in the database, in transactional functions: the interface only calls them. So even someone talking straight to the API cannot skip any of them.',
        'And the physical circuit is inside too: purchase orders, receipts and vouchers as PDFs with signature lines, the official exchange rate for purchases in dollars, and alerts for overdue requests, delayed transfers and stock below minimum.',
      ],
      nodes: {
        consulta: {
          label: 'Site managers and management',
          sub: 'read-only role: see everything, request purchases',
          desc: 'The people who need to know what there is and ask for material. They see the whole system and only write their own purchase requests and dashboard preferences.',
        },
        operario: {
          label: 'Logistics and warehouse',
          sub: 'operator role: record movements and catalogs',
          desc: 'The people who move material. They record purchases, receipts, transfers, vouchers, adjustments and catalogs, and handle anyone’s purchase requests. They do not touch users.',
        },
        admin: {
          label: 'Administrator',
          sub: 'all of the above, plus users and roles',
          desc: 'The only one who manages users. Public sign-up is closed: profiles are born inactive until an admin activates them.',
        },
        app: {
          label: 'Web app',
          sub: 'requests · purchases · transfers · vouchers · tools · adjustments · ledger · dashboard with widgets and alerts',
          desc: 'One screen per operation and live queries. The interface never calculates stock or costs: it asks the database.',
          bullets: [
            'A dashboard each user assembles with the widgets they need.',
            'Ledger per warehouse or site for any period; one article across every warehouse at once.',
            'Hiding buttons per role is ergonomics: real authorization is in the database.',
          ],
        },
        base: {
          label: 'Database (PostgreSQL)',
          sub: 'transactional functions · immutable ledger · balances per warehouse · row-level security',
          desc: 'Every business rule lives here. Each operation is a function that validates the role and the rules and records the movement, all in one transaction.',
          bullets: [
            'Movement tables have no write policies: the functions are the only door.',
            'The ledger is insert-only; correcting means posting the reversal.',
            'Weighted average cost, frozen on every movement.',
          ],
        },
        alertas: {
          label: 'Alerts',
          sub: 'overdue or due-soon requests · delayed transfers · stock below minimum',
          desc: 'Derived from the real state, not from reminders typed in by hand. They show up in the system’s bell.',
        },
        pdf: {
          label: 'Paperwork for the physical circuit',
          sub: 'purchase order, receipt and voucher as PDFs with signature lines',
          desc: 'The supplier, the truck and the site sign on paper. The PDF comes from the same document that records the movement.',
        },
        bcu: {
          label: 'Official exchange rate',
          sub: 'for purchases in dollars, cached per day',
          desc: 'Purchases coexist in pesos and dollars with their currency recorded; the system takes the official rate for the date and stores it.',
        },
      },
      edges: {
        'consulta>app': 'look up and request',
        'operario>app': 'record movements',
        'admin>app': 'administers',
        'app>base': 'every operation is a function in the database',
        'app>alertas': 'notifies',
        'app>pdf': 'prints',
        'app>bcu': 'looks up',
      },
      groups: { gq: 'WHO USES IT', ga: 'THE APPLICATION', gx: 'OUTWARDS' },
      tour: [
        'Three kinds of user enter the same app: site managers and management look things up and request purchases; logistics and warehouse staff record every movement; the admin also manages users.',
        'The app has one screen per operation: requests, purchases, transfers, vouchers, tools, adjustments, ledger and a dashboard with widgets and alerts.',
        'No screen calculates stock: every operation is a transactional function in the database, which validates the role and the rules and records the movement in an immutable ledger.',
        'The physical circuit is part of it too: purchase orders, receipts and vouchers come out as PDFs with signature lines, and purchases in dollars take the day’s official exchange rate.',
        'And the system warns on its own: overdue or due-soon requests, delayed transfers and stock below minimum, derived from the real state.',
      ],
    },
    circuito: {
      name: 'The material circuit',
      intro:
        'From a site’s request to the settlement of what was used, every step is a numbered document with its own status. Above, who takes part in each stretch; below, the other ways stock comes in.',
      nodes: {
        obra: { label: 'Site manager', sub: 'requests what they need, with destination and deadline', desc: 'Any user can request; logistics decides how to buy it.' },
        proveedor: { label: 'Supplier', sub: 'delivers against the purchase order', desc: 'One order can involve several: each line is bought from whoever suits, and feeds a price history per article and supplier.' },
        camion: { label: 'Truck and people', sub: 'assigned to the move', desc: 'Every transfer records the truck and the people travelling with the material.' },
        obra2: { label: 'Site', sub: 'receives the material and answers for it', desc: 'What is consumed is charged to the site’s expenses; what comes back re-enters stock.' },
        pedido: {
          label: 'Purchase request',
          sub: 'open → in progress → fulfilled | cancelled',
          desc: 'What a site or warehouse needs, with destination and deadline. Logistics fulfils it by building purchase orders, or can cancel it with a reason.',
        },
        oc: {
          label: 'Purchase order',
          sub: 'draft → issued → partial receipt → received → closed | cancelled',
          desc: 'Lines that can go to different suppliers. Issuing it fixes the prices in the history; it comes out as a PDF with signature lines.',
          bullets: ['Closing with shortfalls is an explicit decision, with a reason.', 'Closed is terminal: it does not reopen.'],
        },
        recepcion: {
          label: 'Receipt in batches',
          sub: 'what arrived in each delivery; can be partial',
          desc: 'Each batch records the entry into the warehouse at the order’s cost. Voiding a receipt posts the reverse entry.',
        },
        deposito: {
          label: 'Warehouse',
          sub: 'balance per article, kept by the database',
          desc: 'The balance is not edited: it is the sum of the movements. It includes the virtual warehouses IN TRANSIT and REPAIR.',
        },
        transferencia: {
          label: 'Transfer “on the road”',
          sub: 'in transit → partial receipt → received | cancelled',
          desc: 'While it travels, the material is in neither warehouse: it is IN TRANSIT, with a truck and people assigned.',
        },
        recepdest: {
          label: 'Receipt at destination',
          sub: 'in batches, with closure for shortfalls',
          desc: 'The destination receives in batches; what did not arrive is written off explicitly, with a reason.',
        },
        vale: {
          label: 'Consumption voucher',
          sub: 'open → settled | voided',
          desc: 'What leaves the warehouse for a site. Tools go by serial number.',
        },
        rendicion: {
          label: 'Settlement',
          sub: 'what was used is charged to the site; what comes back re-enters at the voucher’s cost',
          desc: 'Closes the voucher: each line says how much was used and how much came back. The settlement has to add up.',
        },
        entrada: { label: 'Direct entry', sub: 'stock that arrives without a purchase order', desc: 'With cost and reason; same entry as a receipt.' },
        ajuste: { label: 'Inventory adjustment', sub: 'count differences, with a mandatory reason', desc: 'Adds or subtracts with its numbered document. Never an edit of the balance.' },
      },
      edges: {
        'obra>pedido': 'requests',
        'pedido>oc': 'logistics builds',
        'oc>recepcion': 'in batches',
        'proveedor>recepcion': 'delivers',
        'recepcion>deposito': 'adds stock at cost',
        'entrada>deposito': 'without an order',
        'ajuste>deposito': 'with a reason',
        'deposito>transferencia': 'leaves',
        'camion>transferencia': 'travels',
        'transferencia>recepdest': 'in transit',
        'recepdest>vale': 'from the warehouse',
        'vale>obra2': 'goes out to site',
        'vale>rendicion': 'is settled',
        'rendicion>obra2': 'usage is charged',
      },
      groups: { gc: 'THE MATERIAL CIRCUIT', gq: 'WHO TAKES PART', go: 'OTHER WAYS STOCK COMES IN' },
      tour: [
        'It starts with a request: any user, a site manager included, asks for what they need with destination and deadline. Logistics fulfils it by building purchase orders.',
        'The order fixes prices and comes out as a PDF. The supplier delivers in batches: each receipt adds stock to the warehouse at the order’s cost; closing with shortfalls is an explicit decision.',
        'When material goes from one warehouse to another it passes through a real state: in transit, with a truck and people. Only when received at destination does it count there.',
        'What goes out to a site goes by voucher and is settled: what was used is charged to the site’s expenses and what comes back re-enters at the voucher’s frozen cost.',
        'Stock also comes in without a purchase order and gets adjusted for count differences, always with a document and a reason. Never by editing the balance.',
      ],
    },
    kardex: {
      name: 'Ledger and costing',
      intro:
        'The chain that turns an operation into a defensible number: document, immutable movement, balance per warehouse and reports. On the sides, the guarantees and what is derived.',
      nodes: {
        operacion: { label: 'An operation', sub: 'received purchase, transfer, voucher, settlement, adjustment…', desc: 'Anything that changes stock comes in here.' },
        documento: {
          label: 'Numbered document',
          sub: 'type (PO, receipt, entry, transfer, voucher, adjustment, repair…), sequential number, user and date',
          desc: 'The database assigns the number atomically: two simultaneous operations never share it.',
        },
        movimientos: {
          label: 'Stock movements',
          sub: 'insert-only; correcting means posting the reversal',
          desc: 'The ledger. Each row states article, warehouse, signed quantity, frozen cost and the document that explains it.',
        },
        saldos: {
          label: 'Balances per warehouse',
          sub: 'kept by a trigger · quantity ≥ 0 always',
          desc: 'Derived from the movements, never edited. The constraint on the table makes negative stock impossible.',
        },
        reportes: {
          label: 'Reports',
          sub: 'ledger at a date · one article across all warehouses · stock per site',
          desc: 'Everything is answered from the movements: what was in a warehouse on a given day, where each unit went.',
        },
        anular: {
          label: 'Void',
          sub: 'posts the reverse entry; history stays',
          desc: 'There is no silent correction. Voiding a receipt, a voucher or a settlement inserts the opposite movement, with a reason.',
        },
        concurrencia: {
          label: 'Two operations at once',
          sub: 'locks in a fixed order; the constraint blocks negatives',
          desc: 'Functions take the lines always in the same order so they do not deadlock, and if two consumptions compete for the same stock, the second fails instead of leaving a negative balance.',
        },
        ppp: {
          label: 'Weighted average cost',
          sub: 'per article, frozen on every movement',
          desc: 'Each costed entry moves the average; each exit takes the cost of the moment and leaves it written down.',
          bullets: ['A transfer does not alter the average.', 'A voucher return re-enters at the voucher’s cost.', 'An unvalued opening load does not touch it.'],
        },
        virtuales: {
          label: 'Virtual warehouses',
          sub: 'IN TRANSIT and REPAIR',
          desc: 'What travels or sits at the repair shop is stock too. So the sum of all balances always equals the company’s real stock.',
        },
        valorizado: {
          label: 'Valued stock',
          sub: 'quantity × average cost, per warehouse and per site',
          desc: 'A number you can defend: it comes from movements with frozen cost, not from an estimate.',
        },
      },
      edges: {
        'operacion>documento': 'numbered, with user and date',
        'documento>movimientos': 'records',
        'movimientos>saldos': 'trigger',
        'saldos>reportes': 'are queried',
        'anular>movimientos': 'reverse entry',
        'concurrencia>saldos': 'quantity ≥ 0',
        'movimientos>ppp': 'cost of the moment',
        'saldos>virtuales': 'balances too',
        'reportes>valorizado': 'frozen cost',
      },
      groups: { gk: 'THE CHAIN', gr: 'WHAT IS DERIVED', gg: 'GUARANTEES' },
      tour: [
        'Every operation is born as a numbered document, with user and date. The database assigns the number atomically.',
        'The document records movements in the ledger, which is insert-only. Correcting means posting the reversal: history stays complete.',
        'A trigger keeps the balances per warehouse and a constraint makes negatives impossible, even with two operations at once. What travels or sits at the repair shop is a balance too, in virtual warehouses.',
        'Each movement carries its frozen cost, with a weighted average per article: transfers do not alter it and returns go back at the voucher’s cost.',
        'That is why the reports are defensible numbers: ledger at a date, one article across all warehouses and valued stock per warehouse and per site.',
      ],
    },
    herramientas: {
      name: 'Tools by serial number',
      intro:
        'A grinder is not “3 grinders”: it is this one, with its serial number. Every unit has its own life cycle and someone answers for it.',
      nodes: {
        serie: { label: 'Unit with serial number', sub: 'each physical tool, its own row', desc: 'Tools are loaded per unit; materials, per quantity.' },
        disponible: { label: 'Available', sub: 'in a warehouse', desc: 'Ready to go out on a voucher.' },
        vale: { label: 'Goes out on a voucher', sub: 'to a site, unit by unit', desc: 'The voucher names each serial that leaves.' },
        enobra: { label: 'On site', sub: 'the site answers for it', desc: 'While out, it shows in the site’s warehouse.' },
        rendicion: { label: 'Settlement', sub: 'unit by unit, one outcome each', desc: 'When the voucher is settled, each tool comes back, goes to repair, or is declared broken or lost.' },
        devuelta: { label: 'Returned', sub: 'back to available', desc: 'Re-enters the warehouse it came from.' },
        areparacion: {
          label: 'To repair',
          sub: 'repair order · virtual warehouse REPAIR',
          desc: 'The unit goes to the shop with its order. If it comes back repaired it is available again; if not, it is written off.',
        },
        rota: { label: 'Broken', sub: 'charged to the site', desc: 'Leaves stock and stays charged to the site that had it.' },
        perdida: { label: 'Lost', sub: 'charged to the site', desc: 'Same as broken: written off stock with someone responsible.' },
        baja: { label: 'Written off', sub: 'discarded after repair', desc: 'The shop declared it beyond repair.' },
      },
      edges: {
        'serie>disponible': 'is registered',
        'disponible>vale': 'goes out on a voucher',
        'vale>enobra': 'arrives',
        'enobra>rendicion': 'is settled',
        'areparacion>baja': 'beyond repair',
      },
      groups: { gc: 'LIFE CYCLE', gr: 'WHAT CAN HAPPEN AT SETTLEMENT' },
      tour: [
        'Each tool is a unit with a serial number and its own row; materials, on the other hand, are counted by quantity.',
        'It goes out to the site on a voucher, named serial by serial, and while it is out it shows in that site’s warehouse.',
        'When the voucher is settled, each unit has a fate: back to the warehouse, to repair, or declared broken or lost. Broken and lost are charged to the site that had it.',
        'Those going to repair move to the virtual warehouse REPAIR with their order: if they come back repaired they are available; if not, they are written off.',
      ],
    },
    arquitectura: {
      name: 'How it is built',
      intro:
        'The rules live in the database, not in the interface. Who gets in, which layers an operation crosses and what happens with every push to production.',
      nodes: {
        admin: { label: 'Admin', sub: 'operates, manages catalogs and users' },
        operario: { label: 'Operator', sub: 'logistics and warehouse: records everything, no users' },
        consulta: { label: 'Read-only', sub: 'site managers and management: reads everything, writes own requests' },
        ui: {
          label: 'Screens (Next.js)',
          sub: 'server actions that return success or failure, never throw · role gates as ergonomics',
          desc: 'The interface shows and asks. It does not calculate stock, costs or statuses.',
        },
        api: {
          label: 'Self-hosted Supabase',
          sub: 'login by username · sign-up closed · profiles born inactive until an admin activates them',
          desc: 'PostgreSQL, auth and API running on the company’s own server, not in a third-party cloud.',
        },
        rpc: {
          label: 'Transactional functions',
          sub: 'validate role and rules in one transaction · errors with a code and a human message',
          desc: 'Every operation is a function. Its first line checks the caller may record; business errors carry a code and its translation for the person.',
        },
        tablas: {
          label: 'Tables with row-level security',
          sub: 'movement tables have no write policies: the functions are the only door',
          desc: 'Even someone talking straight to the API cannot insert a movement outside the rules.',
        },
        push: { label: 'Push to main', sub: 'the only road to production' },
        ci: {
          label: 'Verification in CI',
          sub: 'typecheck, lint and the SQL suite, with migrations applied from scratch',
          desc: 'Runs on every pull request and every push. If it fails, production is untouched.',
        },
        migraciones: { label: 'Migrations to production', sub: 'only if verification passed', desc: 'The schema is versioned; a new business rule is a migration, not a conditional in the interface.' },
        coolify: { label: 'The app redeploys', sub: 'automatic, no downtime', desc: 'The new container carries the commit SHA so you know which version runs.' },
        smoke: {
          label: 'SQL smoke suite',
          sub: 'runs inside a transaction that is rolled back · ~160 assertions',
          desc: 'Tests the real core against the real database without dirtying it: numbering, costing, partial receipts, settlements, serial-numbered tools, roles and permissions.',
        },
      },
      edges: {
        'ui>api': 'session + calls',
        'api>rpc': 'every operation',
        'rpc>tablas': 'records',
        'push>ci': 'verifies',
        'ci>migraciones': 'if it passes',
        'push>coolify': 'redeploys',
        'migraciones>tablas': 'schema',
        'smoke>tablas': 'tests',
      },
      groups: { gq: 'WHO GETS IN', gl: 'LAYERS', gd: 'EVERY PUSH TO MAIN' },
      tour: [
        'Three roles enter through the same screens; the interface hides what does not apply, but that is ergonomics: real authorization sits further down.',
        'An operation goes down the layers: the screen calls, the API authenticates, the transactional function validates role and rules, and only then is it recorded in tables nobody can write to any other way.',
        'The core is tested where it lives: an SQL suite runs inside a transaction that is rolled back, against the real database.',
        'Every push to main goes through verification in CI with migrations applied from scratch; only if it passes are they applied to production. The app redeploys on its own.',
      ],
    },
  },
};

export const stock: DiagramProjectData = { id: 'stock', slug: '/stock', layout, texts: { es, en } };
