import type { Locale } from '../content';
import type { SystemDiagramUi } from './types';

/** Textos comunes a todos los diagramas interactivos. La cabecera va por proyecto. */
export const diagramUi: Record<Locale, SystemDiagramUi> = {
  es: {
    hint: 'Arrastrá las cajas para acomodarlas (cada vista abre ordenada). Clic en una caja para ver el detalle. Ctrl + rueda o los botones para acercar; fondo para desplazar. Esc limpia, F ajusta.',
    tabsAria: 'Vistas del diagrama',
    tourStart: 'Explicar paso a paso',
    tourExit: 'Salir de la explicación',
    fit: 'Ajustar',
    fitTitle: 'Encuadrar el diagrama en la pantalla (F)',
    reset: 'Reordenar',
    resetTitle: 'Volver a la disposición original de esta vista',
    exportSvg: 'Exportar SVG',
    exportTitle: 'Descargar la vista actual como archivo SVG',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    cursorDrag: 'mover',
    viewOf: 'Vista {i} de {n}',
    stepOf: 'Paso {i} de {n}',
    prev: 'Anterior',
    next: 'Siguiente',
    finish: 'Terminar',
    exit: 'Salir',
    tourHint: 'Podés seguir moviendo cajas mientras explicás. Las flechas del teclado cambian de paso.',
    clickHint: 'Hacé clic en una caja para ver qué es y con quién se conecta. Arrastrá para acomodar; «Reordenar» vuelve al orden original.',
    connections: 'Conexiones',
    backToView: 'Volver a la vista',
    scriptTitle: 'Guion de dos minutos',
    svgAria: 'Diagrama interactivo del sistema',
    back: 'Volver',
    backFull: 'Volver al case study',
    switchLabel: 'EN',
    switchAria: 'Ver el diagrama en inglés',
    backCase: 'Volver al case study',
    ctaTalk: 'Hablemos del proyecto',
    overview: 'Vista general',
    pinchHint: 'Pellizcá para acercar · arrastrá para moverte',
    sheetExpand: 'Mostrar el panel',
    sheetCollapse: 'Ocultar el panel',
    stepShort: '{i}/{n}',
    tourStartShort: 'Explicar',
    touchHint: 'Tocá una caja para ver qué es y con quién se conecta. Movete con un dedo y pellizcá para acercar; «Reordenar» vuelve al orden original.',
  },
  en: {
    hint: 'Drag the boxes to arrange them (every view opens tidy). Click a box to see its details. Ctrl + wheel or the buttons to zoom; drag the background to pan. Esc clears, F fits.',
    tabsAria: 'Diagram views',
    tourStart: 'Explain step by step',
    tourExit: 'Exit the walkthrough',
    fit: 'Fit',
    fitTitle: 'Fit the diagram to the screen (F)',
    reset: 'Rearrange',
    resetTitle: 'Restore the original layout of this view',
    exportSvg: 'Export SVG',
    exportTitle: 'Download the current view as an SVG file',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    cursorDrag: 'drag',
    viewOf: 'View {i} of {n}',
    stepOf: 'Step {i} of {n}',
    prev: 'Previous',
    next: 'Next',
    finish: 'Finish',
    exit: 'Exit',
    tourHint: 'You can keep moving boxes while you explain. The arrow keys change step.',
    clickHint: 'Click a box to see what it is and what it connects to. Drag to arrange; “Rearrange” restores the original layout.',
    connections: 'Connections',
    backToView: 'Back to the view',
    scriptTitle: 'Two-minute script',
    svgAria: 'Interactive system diagram',
    back: 'Back',
    backFull: 'Back to the case study',
    switchLabel: 'ES',
    switchAria: 'View the diagram in Spanish',
    backCase: 'Back to the case study',
    ctaTalk: "Let's talk about the project",
    overview: 'Overview',
    pinchHint: 'Pinch to zoom · drag to pan',
    sheetExpand: 'Show the panel',
    sheetCollapse: 'Hide the panel',
    stepShort: '{i}/{n}',
    tourStartShort: 'Explain',
    touchHint: 'Tap a box to see what it is and what it connects to. Drag with one finger and pinch to zoom; “Rearrange” restores the original layout.',
  },
};
